# check, change and merge household income tables

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

In [3]:
# get data
# Define file path
path = r'/Users/alison/Documents/Data Analysis - Tasks/6.1' 
# Get income dfs
ten_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2010_clean.pkl'))
eleven_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2011_clean.pkl'))
twelve_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2012_clean.pkl'))
thirteen_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2013_clean.pkl'))
fourteen_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2014_clean.pkl'))
fifteen_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2015_clean.pkl'))
sixteen_df = pd.read_pickle(os.path.join(path, '02 Data','Prepared', '2016_clean.pkl'))

In [5]:
ten_df.shape

(1459, 6)

In [7]:
ten_df.head()

,GEO_ID,County,State,2010 Median Income,Census_Tract,NAME
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington"
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington"
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington"
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington"

In [9]:
eleven_df.shape

(1459, 6)

In [11]:
eleven_df.head()

,GEO_ID,County,State,2011 Median Income,Census_Tract,NAME
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name
1,1400000US53001950100,Adams County,Washington,43575,Census Tract 9501,"Census Tract 9501, Adams County, Washington"
2,1400000US53001950200,Adams County,Washington,40395,Census Tract 9502,"Census Tract 9502, Adams County, Washington"
3,1400000US53001950300,Adams County,Washington,42393,Census Tract 9503,"Census Tract 9503, Adams County, Washington"
4,1400000US53001950400,Adams County,Washington,41821,Census Tract 9504,"Census Tract 9504, Adams County, Washington"

In [21]:
# merge tables on Census_Tract
merged_df = ten_df.merge(eleven_df, on = ['GEO_ID','NAME'], indicator = True)

In [23]:
merged_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,County_y,State_y,2011 Median Income,Census_Tract_y,_merge
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,None,None,0,Geographic Area Name,both
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",Adams County,Washington,43575,Census Tract 9501,both
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",Adams County,Washington,40395,Census Tract 9502,both
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",Adams County,Washington,42393,Census Tract 9503,both
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",Adams County,Washington,41821,Census Tract 9504,both

In [25]:
merged_df.shape

(1459, 11)

In [27]:
merged_df.isnull().sum()

GEO_ID                0
County_x              1
State_x               1
2010 Median Income    0
Census_Tract_x        0
NAME                  0
County_y              1
State_y               1
2011 Median Income    0
Census_Tract_y        0
_merge                0
dtype: int64

In [37]:
merged_df.drop(columns=['_merge'], inplace=True)

In [39]:
merged_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821

In [31]:
merged_df.shape

(1459, 8)

In [41]:
# merge next tables on Census_Tract
three_df = merged_df.merge(twelve_df, on = ['GEO_ID','NAME'], indicator = True)

In [43]:
three_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,County,State,2012 Median Income,Census_Tract,_merge
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,None,None,0,Geographic Area Name,both
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,Adams County,Washington,44282,Census Tract 9501,both
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,Adams County,Washington,36371,Census Tract 9502,both
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,Adams County,Washington,42391,Census Tract 9503,both
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,Adams County,Washington,42193,Census Tract 9504,both

In [45]:
three_df.shape

(1459, 12)

In [47]:
three_df.isnull().sum()

GEO_ID                0
County_x              1
State_x               1
2010 Median Income    0
Census_Tract_x        0
NAME                  0
2011 Median Income    0
County                1
State                 1
2012 Median Income    0
Census_Tract          0
_merge                0
dtype: int64

In [49]:
# drop columns _y: Census_Tract_y, State_y, County_y
three_df.drop(columns=['County','State', 'Census_Tract', '_merge'], inplace=True)

In [51]:
three_df.shape

(1459, 8)

In [53]:
three_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193

In [55]:
thirteen_df.shape

(1459, 6)

In [57]:
# merge next tables on Census_Tract
four_df = three_df.merge(thirteen_df, on = ['GEO_ID','NAME'], indicator = True)

In [59]:
four_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income,County,State,2013 Median Income,Census_Tract,_merge
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,None,None,0,Geographic Area Name,both
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,Adams County,Washington,43934,Census Tract 9501,both
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,Adams County,Washington,46761,Census Tract 9502,both
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,Adams County,Washington,45600,Census Tract 9503,both
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,Adams County,Washington,39559,Census Tract 9504,both

In [61]:
four_df.shape

(1459, 13)

In [63]:
# drop columns: Census_Tract, State, County, _merge
four_df.drop(columns=['County','State', 'Census_Tract', '_merge'], inplace=True)

In [65]:
four_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income,2013 Median Income
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,0
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,43934
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,46761
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,45600
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,39559

In [67]:
four_df.isnull().sum()

GEO_ID                0
County_x              1
State_x               1
2010 Median Income    0
Census_Tract_x        0
NAME                  0
2011 Median Income    0
2012 Median Income    0
2013 Median Income    0
dtype: int64

In [69]:
fourteen_df.shape

(1459, 6)

In [71]:
fourteen_df.columns

Index(['GEO_ID', 'County', 'State', '2014 Median Income', 'Census_Tract',
       'NAME'],
      dtype='object')

In [73]:
# merge next tables on Census_Tract
five_df = four_df.merge(fourteen_df, on = ['GEO_ID','NAME'], indicator = True)

In [75]:
five_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income,2013 Median Income,County,State,2014 Median Income,Census_Tract,_merge
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,0,None,None,0,Geographic Area Name,both
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,43934,Adams County,Washington,47148,Census Tract 9501,both
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,46761,Adams County,Washington,47833,Census Tract 9502,both
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,45600,Adams County,Washington,45568,Census Tract 9503,both
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,39559,Adams County,Washington,40975,Census Tract 9504,both

In [77]:
five_df.shape

(1459, 14)

In [79]:
# drop columns: Census_Tract, State, County, _merge
five_df.drop(columns=['County','State', 'Census_Tract', '_merge'], inplace=True)

In [81]:
five_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income,2013 Median Income,2014 Median Income
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,0,0
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,43934,47148
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,46761,47833
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,45600,45568
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,39559,40975

In [83]:
fifteen_df.shape

(1459, 6)

In [85]:
# merge next tables on Census_Tract
six_df = five_df.merge(fifteen_df, on = ['GEO_ID','NAME'], indicator = True)

In [87]:
six_df.shape

(1459, 15)

In [89]:
six_df.head()

,GEO_ID,County_x,State_x,2010 Median Income,Census_Tract_x,NAME,2011 Median Income,2012 Median Income,2013 Median Income,2014 Median Income,County,State,2015 Median Income,Census_Tract,_merge
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,0,0,None,None,0,Geographic Area Name,both
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,43934,47148,Adams County,Washington,47535,Census Tract 9501,both
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,46761,47833,Adams County,Washington,52500,Census Tract 9502,both
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,45600,45568,Adams County,Washington,39276,Census Tract 9503,both
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,39559,40975,Adams County,Washington,41522,Census Tract 9504,both

In [91]:
# drop columns: Census_Tract, State, County, _merge
six_df.drop(columns=['County','State', 'Census_Tract', '_merge'], inplace=True)

In [93]:
six_df.columns

Index(['GEO_ID', 'County_x', 'State_x', '2010 Median Income', 'Census_Tract_x',
       'NAME', '2011 Median Income', '2012 Median Income',
       '2013 Median Income', '2014 Median Income', '2015 Median Income'],
      dtype='object')

In [95]:
six_df.shape

(1459, 11)

In [97]:
sixteen_df.shape

(1459, 6)

In [99]:
sixteen_df.columns

Index(['GEO_ID', 'County', 'State', '2016 Median Income', 'Census_Tract',
       'NAME'],
      dtype='object')

In [101]:
# merge last table on GEO_ID, NAME
seven_df = six_df.merge(sixteen_df, on = ['GEO_ID','NAME'], indicator = True)

In [103]:
seven_df.shape

(1459, 16)

In [105]:
seven_df.columns

Index(['GEO_ID', 'County_x', 'State_x', '2010 Median Income', 'Census_Tract_x',
       'NAME', '2011 Median Income', '2012 Median Income',
       '2013 Median Income', '2014 Median Income', '2015 Median Income',
       'County', 'State', '2016 Median Income', 'Census_Tract', '_merge'],
      dtype='object')

In [107]:
# drop columns: Census_Tract, State, County, _merge
seven_df.drop(columns=['County','State', 'Census_Tract', '_merge'], inplace=True)

In [109]:
seven_df.columns

Index(['GEO_ID', 'County_x', 'State_x', '2010 Median Income', 'Census_Tract_x',
       'NAME', '2011 Median Income', '2012 Median Income',
       '2013 Median Income', '2014 Median Income', '2015 Median Income',
       '2016 Median Income'],
      dtype='object')

In [111]:
# tidy up final df
# rename columns 
seven_df.rename(columns = {'County_x' : 'County', 'State_x': 'State', 'Census_Tract_x': 'Census_Tract'}, inplace = True)

In [113]:
seven_df.head()

,GEO_ID,County,State,2010 Median Income,Census_Tract,NAME,2011 Median Income,2012 Median Income,2013 Median Income,2014 Median Income,2015 Median Income,2016 Median Income
0,Geography,None,None,0,Geographic Area Name,Geographic Area Name,0,0,0,0,0,0
1,1400000US53001950100,Adams County,Washington,42039,Census Tract 9501,"Census Tract 9501, Adams County, Washington",43575,44282,43934,47148,47535,47250
2,1400000US53001950200,Adams County,Washington,44828,Census Tract 9502,"Census Tract 9502, Adams County, Washington",40395,36371,46761,47833,52500,54667
3,1400000US53001950300,Adams County,Washington,41686,Census Tract 9503,"Census Tract 9503, Adams County, Washington",42393,42391,45600,45568,39276,40992
4,1400000US53001950400,Adams County,Washington,39013,Census Tract 9504,"Census Tract 9504, Adams County, Washington",41821,42193,39559,40975,41522,36372

In [115]:
# Move column '2010 Median Income' two places to the right
column_to_move = '2010 Median Income'
new_position = seven_df.columns.get_loc(column_to_move) + 2  # Current position + 2

# Create new column order
columns = seven_df.columns.tolist()
# Remove the column from its original position
columns.remove(column_to_move)
# Insert the column at the new position
columns.insert(new_position, column_to_move)

# Reassign the columns to the DataFrame
seven_df = seven_df[columns]

In [117]:
seven_df.head()

,GEO_ID,County,State,Census_Tract,NAME,2010 Median Income,2011 Median Income,2012 Median Income,2013 Median Income,2014 Median Income,2015 Median Income,2016 Median Income
0,Geography,None,None,Geographic Area Name,Geographic Area Name,0,0,0,0,0,0,0
1,1400000US53001950100,Adams County,Washington,Census Tract 9501,"Census Tract 9501, Adams County, Washington",42039,43575,44282,43934,47148,47535,47250
2,1400000US53001950200,Adams County,Washington,Census Tract 9502,"Census Tract 9502, Adams County, Washington",44828,40395,36371,46761,47833,52500,54667
3,1400000US53001950300,Adams County,Washington,Census Tract 9503,"Census Tract 9503, Adams County, Washington",41686,42393,42391,45600,45568,39276,40992
4,1400000US53001950400,Adams County,Washington,Census Tract 9504,"Census Tract 9504, Adams County, Washington",39013,41821,42193,39559,40975,41522,36372

In [119]:
# check for missing values#
seven_df.isnull().sum()

GEO_ID                0
County                1
State                 1
Census_Tract          0
NAME                  0
2010 Median Income    0
2011 Median Income    0
2012 Median Income    0
2013 Median Income    0
2014 Median Income    0
2015 Median Income    0
2016 Median Income    0
dtype: int64

In [121]:
# check for duplicate values
# Check for duplicates

dups = seven_df.duplicated()
dups.sum()

# No dups!

0

In [123]:
# export df
seven_df.to_pickle(os.path.join(path, '02 Data','Prepared', 'WA_HI_2010_to_2016.pkl'))

In [125]:
seven_df.groupby('County').agg({'2010 Median Income':['mean', 'min', 'max'], 
                         '2011 Median Income':['mean', 'min', 'max'], 
                         '2012 Median Income':['mean', 'min', 'max'],
                          '2013 Median Income':['mean', 'min', 'max'], '2014 Median Income':['mean', 'min', 'max'], '2015 Median Income':['mean', 'min', 'max'], '2016 Median Income':['mean', 'min', 'max']})

                    2010 Median Income                2011 Median Income  \
                                  mean    min     max               mean
County
Adams County              40619.000000  35529   44828       40697.800000
Asotin County             43394.333333  26641   57091       44720.500000
Benton County             61113.918919      0  112431       62355.378378
Chelan County             53677.000000  38142   87372       54568.214286
Clallam County            42716.500000      0   56378       44212.500000
Clark County              59647.240385  24396  109952       60480.028846
Columbia County           43611.000000  43611   43611       44038.000000
Cowlitz County            45153.833333  17545   70120       46335.708333
Douglas County            48995.625000  35370   65104       49533.250000
Ferry County              36236.333333  34026   40444       35962.333333
Franklin County           46141.461538      0   79632       47596.538462
Garfield County           42269.000000  42269   42269       47379.000000
Grant County              43573.500000  27258   64926       46977.375000
Grays Harbor County       39389.941176      0   61193       39411.588235
Island County             53779.818182      0   75757       56942.409091
Jefferson County          38767.250000      0   61118       40587.375000
King County               73499.407035      0  184375       75622.550251
Kitsap County             60706.363636      0  114375       62195.090909
Kittitas County           43169.750000  16945   62976       43389.375000
Klickitat County          39947.000000  31102   45940       41555.666667
Lewis County              45101.700000  30599   64306       44888.950000
Lincoln County            45871.500000  41102   51961       48077.000000
Mason County              46485.571429  26250   58942       48242.785714
Okanogan County           39367.700000  26366   51477       41324.700000
Pacific County            34171.125000      0   44554       34745.750000
Pend Oreille County       38328.000000  25950   45357       40035.600000
Pierce County             59928.331395  13533  107700       61111.267442
San Juan County           40718.600000      0   59955       40483.400000
Skagit County             52780.100000      0   76405       53640.966667
Skamania County           51338.200000  41853   69792       55275.000000
Snohomish County          69422.874172      0  142778       70786.735099
Spokane County            49122.352381  12813  101830       50778.047619
Stevens County            41126.250000  25838   70489       42198.750000
Thurston County           60390.180000      0  101774       62204.980000
Wahkiakum County          40372.000000  40372   40372       41149.000000
Walla Walla County        41141.166667      0   77321       41830.916667
Whatcom County            49900.764706  16750   81699       51967.852941
Whitman County            40560.600000  12527   67946       39539.700000
Yakima County             44180.733333  17019   78722       44998.622222

                                   2012 Median Income                 \
                       min     max               mean    min     max
County
Adams County         35305   43575       40922.400000  36371   44282
Asotin County        29375   58305       43872.000000  29779   59301
Benton County            0  122529       63120.216216      0  123162
Chelan County        40065   88782       54459.642857  39427   80680
Clallam County           0   61500       43219.636364      0   61095
Clark County         23624  120000       60548.769231  25368  113148
Columbia County      44038   44038       45417.000000  45417   45417
Cowlitz County       17955   68457       45288.666667  12944   68496
Douglas County       36694   64500       51677.250000  36985   70385
Ferry County         34483   36962       33062.666667  26700   37468
Franklin County          0   78292       47327.000000      0   76250
Garfield County      47379   47379       51325.000000  51325   51325
Grant County         27261   67103       47710.437500  30462   68056
Grays Harbor County      0   59000       38578.647059      0   53899
Island County            0   78857       56325.000000      0   78294
Jefferson County         0   66687       40707.250000      0   66993
King County              0  186630       76390.766332      0  190833
Kitsap County            0  122326       62915.254545      0  119375
Kittitas County      17417   68860       42736.000000  16984   64559
Klickitat County     31611   48056       41580.666667  33932   49228
Lewis County         32880   56602       44502.050000  33255   67772
Lincoln County       43286   60387       46656.000000  39784   63485
Mason County         29500   60332       47389.285714  29196   62649
Okanogan County      26905   53667       41156.200000  32692   49271
Pacific County           0   50503       35062.125000      0   48104
Pend Oreille County  29464   49286       39555.200000  24330   52333
Pierce County        18475  116065       61516.005814  18553  114500
San Juan County          0   60319       41226.600000      0   62629
Skagit County            0   78377       53839.066667      0   82153
Skamania County      46406   72237       52182.800000  44844   61806
Snohomish County         0  133571       71297.602649      0  128108
Spokane County       14847  101983       51005.085714  14990   96039
Stevens County       27267   72610       42010.416667  28527   65625
Thurston County          0   94257       61998.920000      0   87135
Wahkiakum County     41149   41149       45335.000000  45335   45335
Walla Walla County       0   78589       43438.916667      0   72217
Whatcom County       21890   81667       52103.058824  18510   78476
Whitman County       13268   66467       40026.000000  10776   66296
Yakima County        19904   78295       45448.533333  17917   78438

                    2013 Median Income  ...         2014 Median Income         \
                                  mean  ...     max               mean    min
County                                  ...
Adams County              44315.000000  ...   46761       45199.200000  40975
Asotin County             42929.833333  ...   60574       43192.000000  28863
Benton County             63547.567568  ...  127358       64329.864865      0
Chelan County             54499.142857  ...   74531       53325.000000  37036
Clallam County            42703.636364  ...   61574       44024.090909      0
Clark County              60128.125000  ...  115793       61491.115385  26703
Columbia County           42519.000000  ...   42519       41071.000000  41071
Cowlitz County            46127.125000  ...   69281       44741.000000  11853
Douglas County            51812.125000  ...   70771       52229.375000  41062
Ferry County              35347.000000  ...   39346       34710.666667  25511
Franklin County           50449.923077  ...   78920       53222.692308      0
Garfield County           51548.000000  ...   51548       50915.000000  50915
Grant County              46670.625000  ...   65670       47525.562500  30282
Grays Harbor County       38469.823529  ...   52065       39793.058824      0
Island County             55547.681818  ...   74764       56441.363636      0
Jefferson County          40007.250000  ...   63502       40221.625000      0
King County               77016.851759  ...  194205       78408.733668      0
Kitsap County             63707.163636  ...  122292       64756.836364      0
Kittitas County           43770.125000  ...   61473       44552.250000  23027
Klickitat County          42775.666667  ...   52370       45525.000000  39492
Lewis County              43064.100000  ...   59818       43340.350000  33194
Lincoln County            48496.000000  ...   62732       48778.750000  42476
Mason County              47581.285714  ...   63302       48146.785714  32292
Okanogan County           42237.100000  ...   51375       42688.500000  34319
Pacific County            34307.000000  ...   49021       33710.625000      0
Pend Oreille County       41385.600000  ...   52997       41077.400000  29965
Pierce County             61762.366279  ...  111838       62133.563953  15050
San Juan County           42400.400000  ...   64583       43129.800000      0
Skagit County             53485.800000  ...   77976       53175.100000      0
Skamania County           51068.600000  ...   62137       48857.200000  40139
Snohomish County          71563.119205  ...  134773       72090.556291      0
Spokane County            50326.009524  ...   97697       51116.676190  14375
Stevens County            41638.583333  ...   62163       42426.916667  28576
Thurston County           61772.820000  ...   92951       62441.600000      0
Wahkiakum County          41815.000000  ...   41815       44500.000000  44500
Walla Walla County        43183.166667  ...   78179       43257.750000      0
Whatcom County            52383.352941  ...   88225       53327.382353  19746
Whitman County            40572.900000  ...   65642       40946.300000   9891
Yakima County             44223.177778  ...   80250       44658.066667  17373

                            2015 Median Income                 \
                        max               mean    min     max
County
Adams County          47833       46340.600000  39276   52500
Asotin County         65278       44732.000000  27809   66613
Benton County        128100       64185.324324      0  134396
Chelan County         74886       54946.857143  35505   79395
Clallam County        62899       44371.500000      0   64159
Clark County         121000       62701.932692  26490  125897
Columbia County       41071       38581.000000  38581   38581
Cowlitz County        71101       46006.541667  16406   69750
Douglas County        75134       52897.250000  43813   71164
Ferry County          39474       35420.000000  26359   40469
Franklin County       80426       52220.153846      0   82636
Garfield County       50915       45855.000000  45855   45855
Grant County          65508       49368.750000  29893   64359
Grays Harbor County   56680       40714.117647      0   59188
Island County         76603       55692.681818      0   77438
Jefferson County      63816       41765.375000      0   61701
King County          188077       80384.304020      0  199542
Kitsap County        149688       65861.945455      0  150769
Kittitas County       65583       45929.500000  23780   64286
Klickitat County      54288       48521.666667  41111   61411
Lewis County          59535       44181.650000  31154   62821
Lincoln County        59357       46974.500000  41366   55724
Mason County          62969       47626.571429  32047   61635
Okanogan County       60694       42335.300000  32357   55042
Pacific County        48359       32241.000000      0   46964
Pend Oreille County   53464       41812.200000  29671   53229
Pierce County        114423       62468.691860  18023  122743
San Juan County       66289       43439.000000      0   69006
Skagit County         81563       52828.700000      0   84777
Skamania County       63482       53084.800000  36205   67695
Snohomish County     135568       73372.927152      0  140625
Spokane County        96694       50631.657143  13868  102996
Stevens County        62724       41800.916667  28184   60918
Thurston County       88816       62242.000000      0   91875
Wahkiakum County      44500       44485.000000  44485   44485
Walla Walla County    68294       44345.250000      0   69021
Whatcom County        82667       53517.941176  20449   82180
Whitman County        66250       41600.000000  14423   61118
Yakima County         67243       45103.333333  19896   65169

                    2016 Median Income
                                  mean    min     max
County
Adams County              46850.000000  36372   54969
Asotin County             46246.666667  27865   66579
Benton County             65799.918919      0  130000
Chelan County             55051.500000  33048   81105
Clallam County            44595.045455      0   64430
Clark County              64958.028846  26858  129671
Columbia County           42083.000000  42083   42083
Cowlitz County            47918.625000  19770   75589
Douglas County            54283.125000  41097   75125
Ferry County              35937.333333  25341   42292
Franklin County           55408.615385      0   91750
Garfield County           51395.000000  51395   51395
Grant County              50510.062500  26932   64231
Grays Harbor County       42168.294118      0   64547
Island County             56591.409091      0   78222
Jefferson County          42804.500000      0   60746
King County               83773.424623      0  201818
Kitsap County             69071.618182      0  212750
Kittitas County           47503.250000  24422   67703
Klickitat County          48668.333333  44167   54215
Lewis County              45437.500000  30536   62019
Lincoln County            48968.750000  41080   54563
Mason County              48350.642857  37408   66321
Okanogan County           43716.700000  32343   61033
Pacific County            33645.500000      0   50372
Pend Oreille County       45116.800000  30448   53649
Pierce County             64008.866279  15104  137596
San Juan County           45975.000000      0   72331
Skagit County             54780.133333      0   90592
Skamania County           49139.400000  37891   64219
Snohomish County          75710.086093      0  148571
Spokane County            51077.733333  13833  103585
Stevens County            44090.083333  30553   60507
Thurston County           63407.380000      0   93810
Wahkiakum County          48116.000000  48116   48116
Walla Walla County        44882.583333      0   68724
Whatcom County            54217.852941  21838   87202
Whitman County            43305.700000  15677   73327
Yakima County             45939.911111  17064   71498

[39 rows x 21 columns]

In [ ]:
# all merged, stayed consistent in shape. Ready to merge with main dataset.